### ISSUE TITLE
Put default values in ingest config, or suggest options in comments

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/pathogen-repo-guide#4]
### Context

Trying out pathogen-repo-template for Nipah and noticing that it would be really nice if there were default values either already in ingest's `defaults.yaml` or if there were comments giving example values.

As is, the pipeline crashes due to `field_map: []` and an empty field map is apparently not accepted.

I'm now looking at monkeypox to see what we do there, but maybe this could be put in comments to save users from having to look at other pipelines.

**Comment by joverlee521** [comment]
Thanks for trying this out @corneliusroemer, I always appreciate more feedback 🙏 

I didn't put any default values in because I wasn't sure what would be appropriate defaults and I wanted users to consciously fill in the config params. Specifically for the `field_map` config, the values could be pretty different depending on if you were using the Entrez records or the NCBI Dataset records. 

We should definitely add more guidance/documentation here. 
What would be more useful, to have separate docs or add more to the config file
https://github.com/nextstrain/pathogen-repo-template/blob/9a184024117b6940e5d21260f942a43437457920/ingest/config/defaults.yaml#L25-L28

**Comment by corneliusroemer** [comment]
You're right that we essentially need two field maps, one for entrez and one for NCBI dataset records.

It might be nice to have default mappings across our pathogen repos - this might mean having them `vendored` and only specifying _overwrites_ in the `defaults.yaml`.

All the user would then have to set is `default_mapping: "entrez" | "NCBI dataset"`

Maybe this is a bad idea as we want field names to not change once they're set. In which case we could maintain two defaults in the template as guidance, to be uncommented or otherwise deleted.

**Comment by joverlee521** [comment]
I can definitely add the default mapping for the [default fields that we ingest from NCBI Datasets](https://github.com/nextstrain/pathogen-repo-template/blob/9a184024117b6940e5d21260f942a43437457920/ingest/rules/fetch_from_ncbi.smk#L104-L121) and make it clear that it would need to be edited for the Entrez route. 

I'm not sure I can provide any default mappings for Entrez. I expect we'd only use Entrez if there's custom fields that need to be parsed, so I've left it very open-ended:
https://github.com/nextstrain/pathogen-repo-template/blob/9a184024117b6940e5d21260f942a43437457920/ingest/rules/fetch_from_ncbi.smk#L43-L53

**Comment by joverlee521** [comment]
Added default mapping for `field_map` in #6
