### ISSUE TITLE
ingest: add rule to create `url` column for accessions

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/pathogen-repo-guide#76]
### Context
Building on discussion in office hours as summarized by @j23414 in https://github.com/nextstrain/pathogen-repo-guide/issues/20#issuecomment-2521387879: 

> During office hours today, it was brought up that "genbank_accession" is [automatically detected in auspice](https://github.com/nextstrain/auspice/blob/bf2481679045fe969185429877d37fd2620de620/src/components/tree/infoPanels/click.js#L76-L78) and generates a GenBank URL for the node callout. However, "accession" is not and does not get a valid link in the node call out. When spiking in non-genbank records (e.g. USVI for zika), we usually generate a url column in the metadata to get a valid link in the node call out.
> 
> It was proposed to generate a URL column during `ingest` workflow, which may subsequently work as-is in the node callout and easier to merge with non-genbank records.

### Description

The ingest workflow should include steps to add a new `url` column. 
Existing examples:
- [zika](https://github.com/nextstrain/zika/blob/649e495a6b181c004bacae26ea4507fc6989abc5/phylogenetic/rules/merge_sequences_usvi.smk#L44-L47)
- [yellow-fever](https://github.com/nextstrain/yellow-fever/commit/3f2e00bb44a2ca681f40bfbc7b3fef838da221ca)

**Comment by j23414** [comment]
Thinking out loud, there seem to be a couple of ways to implement this:

1. Create a new rule (which also creates another intermediate file)
	1. example: https://github.com/nextstrain/pathogen-repo-guide/commit/436805f4cec928366ce9e39aa0cc3e2be59cf995 - mostly moving the rule in [this commit](https://github.com/nextstrain/zika/pull/75/commits/41991ff7fa03cf92e2a6c657687f74f65a6cb425) from the phylogenetic to the ingest workflow
	2. Creating a new rule would be consistent to the [subset_metadata rule](https://github.com/nextstrain/pathogen-repo-guide/blob/a44303852aed25c23d3caece49aa6a6651846cf4/ingest/rules/curate.smk#L120-L131)
	3. Would keep the [curate rule] mostly composed of "augur curate" commands
2. Incorporate the `url` creation into the existing `curate` rule
	1. If we add `url` during the JSON parsing, it requires writing an `append-url.py` script 
		1. Which would trigger adding said script to the `vendored` repo
		2. Which might trigger adding a general purpose `append-x-cols.py`script?
	2. If we add `url` after the JSON parsing but within the rule, this looks like creating an intermediate (metadata_curated.tsv?) upon which csvtk is called.

Just checking if there's any strong preferences between the implementation options?

**Comment by joverlee521** [comment]
I think (1) is easier to understand and I'd prefer not to add another custom script...

If we want to add it to the existing `curate` rule that works with JSONs, we also have the option of adding the new column with `jq`

```sh
echo '{"accession":"123"}' | jq '. |= (.url="https://www.ncbi.nlm.nih.gov/nuccore/" + .accession)'
```

**Comment by genehack** [comment]
> I think (1) is easier to understand and I'd prefer not to add another custom script...
> 
> If we want to add it to the existing `curate` rule that works with JSONs, we also have the option of adding the new column with `jq`
> 
> ```shell
> echo '{"accession":"123"}' | jq '. |= (.url="https://www.ncbi.nlm.nih.gov/nuccore/" + .accession)'
> ```

+1 for option 1 and no additional custom scripts — the [yellow fever version of this](https://github.com/nextstrain/yellow-fever/blob/main/ingest/rules/curate.smk#L130-L133) was easy to add

**Comment by j23414** [comment]
After learning about it, I kinda like the `jq` suggestion as it bypasses writing and tracking yet-another custom script, as well as bypasses generating yet-another intermediate file. Checking if anyone feels there are drawbacks to using jq? I've pasted example jq implementations below

* For guide: https://github.com/nextstrain/pathogen-repo-guide/pull/80/commits/58a9a99d40112250e1f6934cfd9c9db99532383e
* For zika: https://github.com/nextstrain/zika/pull/78

**Comment by genehack** [comment]
> Checking if anyone feels there are drawbacks to using jq (e.g. are jq statements too difficult to understand and maintain)? 

Personally, I am not a huge fan of `jq`. We're already extensively using `cvstk`, and `cvstk` can be used to build the `url` column, so I think the question (again, from my POV) is more "why would we *not* use `csvtk`?"

**Comment by j23414** [comment]
> "why would we not use csvtk?"

My push-back against`csvtk` in this case is the creation of yet-another intermediate file. Could you elaborate on what experiences have led you to not be a huge fan of `jq`? I ask because I haven't used `jq` extensively so I'm wondering what the draw backs of the tool are (e.g. limited streaming, slowness in certain situations, memory limits, changes its api often, conflicts between `jq` variable names and `snakemake` or `python` or `nextstrain-cli`, etc...?). This also has the added benefit that I'll have an argument for or against using `jq` in subsequent code bases.

We might be able to satisfy both requirements (1) use `csvtk` and (2) bypass creation of yet-another-intermediate file by adding it to the "subset_metadata" rule:

* Here: https://github.com/nextstrain/pathogen-repo-guide/blob/a44303852aed25c23d3caece49aa6a6651846cf4/ingest/rules/curate.smk#L129

But let me know if I'm the only one being a sticker on "bypass creation of yet-another intermediate file" (what preferred name do we want?), I'm willing to accept the memory bloat (yes I know temp() files exist) and the subsequent decision on naming a new file. I'm still hopeful of finding a solution that satisfies all expressed requirements (especially if this solution gets propagated across several repositories) but compromises are also acceptable.

**Comment by genehack** [comment]
> > "why would we not use csvtk?"
> 
> My push-back against`csvtk` in this case is the creation of yet-another intermediate file.

If that's a concern, `temp()` or integrating the `csvtk` steps into the existing `curate` rule cascade are both approaches that would work. 

> Could you elaborate on what experiences have led you to not be a huge fan of `jq`?

The syntax for it doesn't stick in my brain, and I constantly have to look it up; it's another, slightly different set of things to remember and understand, but it's not `jq` _specifically_ I'm objecting to, it's adding yet another tool. I'd push back on `sed` in the same way.
